# Generated by Django 3.1.3 on 2021-02-03 20:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210203_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='index.png', null=True, upload_to=posts.models.upload_location),
        ),
    ]
