# Generated by Django 3.1.3 on 2021-01-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210128_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='time',
            new_name='timestamp',
        ),
    ]
